# Generated by Django 4.1 on 2022-08-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0003_command_extra_args_command_target_specifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='response_requested',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('ack', 'ack'), ('status', 'status'), ('complete', 'complete')], help_text='The type of Response required for the Command', max_length=255, null=True, verbose_name='Response Requested'),
        ),
    ]
