# Generated by Django 3.2.3 on 2021-07-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_transportHTTPS_polymorphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOpenDXL',
            fields=[
                ('transportauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.transportauth')),
                ('prefix', models.CharField(blank=True, default='', help_text='Pub/Sub Prefix', max_length=30)),
                ('request_topic', models.CharField(blank=True, default='/oc2/cmd', help_text='Request Topic', max_length=60)),
                ('response_topic', models.CharField(blank=True, default='/oc2/rsp', help_text='Response Topic', max_length=60)),
                ('service_topic', models.CharField(blank=True, default='/oc2', help_text='Service Topic', max_length=60)),
            ],
            options={
                'verbose_name': 'OpenDXL Transport',
            },
            bases=('device.transportauth',),
        ),
    ]
