# Generated by Django 2.2 on 2019-05-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senthistory',
            name='_coap_id',
            field=models.CharField(blank=True, help_text='Unique 16-bit hex ID for CoAP', max_length=10, null=True, unique=True),
        ),
    ]
