# Generated by Django 2.2 on 2019-05-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20190416_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='multi_actuator',
            field=models.BooleanField(default=True, help_text='Device can have multiple actuators or is its own actuator'),
        ),
    ]
