# Generated by Django 2.2.10 on 2020-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20200219_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='channel',
            field=models.CharField(blank=True, default='', help_text='Channel for the specific device, only necessary for Pub/Sub protocols', max_length=30),
        ),
        migrations.AlterField(
            model_name='transport',
            name='topic',
            field=models.CharField(blank=True, default='', help_text='Topic for the specific device, only necessary for Pub/Sub protocols', max_length=30),
        ),
    ]
