# Generated by Django 3.0.9 on 2020-08-17 15:50

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20200422_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='topic',
        ),
        migrations.AddField(
            model_name='transport',
            name='ca_cert',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default='', help_text='CA Certificate'),
        ),
        migrations.AddField(
            model_name='transport',
            name='client_cert',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default='', help_text='Client Certificate'),
        ),
        migrations.AddField(
            model_name='transport',
            name='client_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default='', help_text='Client Key'),
        ),
        migrations.AddField(
            model_name='transport',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, default='', help_text='Authentication password', max_length=50),
        ),
        migrations.AddField(
            model_name='transport',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Authentication Username', max_length=30),
        ),
    ]
