# Generated by Django 3.1.1 on 2020-10-15 16:29

from django.db import migrations, models
import django.db.models.deletion

HTTP_TRANSPORTS = []


def gather_http(apps, schema_editor):
    baseModel = apps.get_model('device', 'transport')
    protocol = apps.get_model('orchestrator', 'protocol').objects.get(name='HTTP')

    for t in baseModel.objects.filter(protocol=protocol):
        d = dict(
            serialization=[s.pk for s in t.serialization.all()],
            **t.__dict__
        )
        d.pop('_state', None)
        d.pop('polymorphic_ctype_id', None)
        HTTP_TRANSPORTS.append(d)


def update_http(apps, schema_editor):
    baseModel = apps.get_model('device', 'transport')
    httpModel = apps.get_model('device', 'transporthttp')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    http_ct = ContentType.objects.get_for_model(httpModel)

    for data in HTTP_TRANSPORTS:
        base_trans = baseModel.objects.get(transport_id=data['transport_id'])
        devs = list(base_trans.device_set.all())
        base_trans.delete()
        serials = data.pop('serialization', [])
        trans = httpModel.objects.create(
            **data,
            polymorphic_ctype=http_ct
        )
        trans.serialization.set(serials)
        trans.save()
        for d in devs:
            d.transport.add(trans)
            d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_transportMQTT_polymorph'),
    ]

    operations = [
        migrations.RunPython(gather_http, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TransportHTTP',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.transport')),
                ('path', models.CharField(blank=True, default='', help_text='URL endpoint path', max_length=60)),
            ],
            options={
                'verbose_name': 'HTTP Transport',
            },
            bases=('device.transport', models.Model),
        ),
        migrations.RunPython(update_http, migrations.RunPython.noop),
    ]
