# Generated by Django 3.2.7 on 2021-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_transportopendxl'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporthttps',
            name='prod',
            field=models.BooleanField(default=False, help_text='Security Level: production or development'),
        ),
    ]
