# Generated by Django 3.2.7 on 2021-12-09 13:48

from django.db import migrations


def update_context(apps, schema_editor):
    http_model = apps.get_model('device', 'transporthttp')
    https_model = apps.get_model('device', 'transporthttps')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    http_ct = ContentType.objects.get_for_model(http_model)
    https_ct = ContentType.objects.get_for_model(https_model)
    http_ct.objects.update(polymorphic_ctype=https_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_transporthttps_prod'),
    ]

    operations = [
        migrations.RunPython(update_context, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='TransportHTTP',
        ),
    ]
