# Generated by Django 3.0.6 on 2020-05-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actuator', '0002_auto_20190417_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='schema_format',
        ),
    ]
