FROM debian:latest

MAINTAINER Screaming_Bunny

LABEL name="Base Debian" \
vendor="Screaming Bunny" \
license="BSD" \
version="2.0" \
description="This is the Base Debian container for Screaming Bunny GUI Building."

ENV NVM_VERSION=0.34.0 \
    NVM_DIR=/usr/share/nvm

# Package installation
# Packages - https://pkgs.alpinelinux.org/packages
RUN apt-get update && \
    apt-get install -y wget tar bzip2 && \
    mkdir -p $NVM_DIR && \
    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
#
RUN echo '#!/bin/bash\nset -e\n. "$NVM_DIR/nvm.sh"\n\necho "$@"\n\neval "$@"' > /entrypoint.sh && \
chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nvm", "--version"]