# Generated by Django 2.1.1 on 2018-10-22 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orchestrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orc_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(default='Orchestrator', max_length=30, unique=True)),
                ('host', models.CharField(default='127.0.0.1', max_length=60)),
                ('port', models.IntegerField(default=0)),
                ('proto', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=5)),
            ],
            options={
                'verbose_name': 'Orchestrator',
            },
        ),
        migrations.CreateModel(
            name='OrchestratorAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('orchestrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.Orchestrator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orchestrator Auth',
            },
        ),
        migrations.AlterUniqueTogether(
            name='orchestrator',
            unique_together={('host', 'port')},
        ),
    ]
