# Generated by Django 2.2.10 on 2020-03-09 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actuator', '0002_auto_20190417_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformanceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.UUIDField(default=uuid.uuid4, help_text='Unique UUID of the test', unique=True)),
                ('test_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the test was run')),
                ('tests_run', jsonfield.fields.JSONField(blank=True, help_text='Tests that were selected for conformance', null=True)),
                ('test_results', jsonfield.fields.JSONField(blank=True, help_text='Tests results', null=True)),
                ('actuator_tested', models.ForeignKey(help_text='Actuator tests were run against', on_delete=django.db.models.deletion.CASCADE, to='actuator.Actuator')),
            ],
        ),
    ]
