# Generated by Django 3.2.12 on 2022-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0003_auto_20220420_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedcommandhistory',
            options={'verbose_name_plural': 'Received Command History'},
        ),
    ]
