# Generated by Django 2.2.7 on 2019-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_remove_device_multi_actuator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='routing_key',
        ),
        migrations.AddField(
            model_name='transport',
            name='channel',
            field=models.CharField(default='routing_key', max_length=30),
        ),
        migrations.AddField(
            model_name='transport',
            name='topic',
            field=models.CharField(default='topic', max_length=30),
        ),
    ]
