# Generated by Django 2.2.9 on 2020-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20191220_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='channel',
            field=models.CharField(default='channel', help_text='Channel for the specific device, only necessary for Pub/Sub protocols', max_length=30),
        ),
        migrations.AlterField(
            model_name='transport',
            name='topic',
            field=models.CharField(default='topic', help_text='Topic for the specific device, only necessary for Pub/Sub protocols', max_length=30),
        ),
    ]
