# Generated by Django 3.0.9 on 2020-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20200817_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text='Pub/Sub Prefix', max_length=30),
        ),
    ]
