# Generated by Django 3.1.1 on 2020-09-11 19:52

from django.db import migrations, models
import django.db.models.deletion

MQTT_TRANSPORTS = []


def gather_mqtt(apps, schema_editor):
    baseModel = apps.get_model('device', 'transport')
    protocol = apps.get_model('orchestrator', 'protocol').objects.get(name='MQTT')

    for t in baseModel.objects.filter(protocol=protocol):
        d = dict(
            serialization=[s.pk for s in t.serialization.all()],
            **t.__dict__
        )
        d.pop('_state', None)
        d.pop('polymorphic_ctype_id', None)
        MQTT_TRANSPORTS.append(d)


def update_mqtt(apps, schema_editor):
    baseModel = apps.get_model('device', 'transport')
    mqttModel = apps.get_model('device', 'transportmqtt')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    mqtt_ct = ContentType.objects.get_for_model(mqttModel)

    for data in MQTT_TRANSPORTS:
        base_trans = baseModel.objects.get(transport_id=data['transport_id'])
        devs = list(base_trans.device_set.all())
        base_trans.delete()
        serials = data.pop('serialization', [])
        trans = mqttModel.objects.create(
            **data,
            polymorphic_ctype=mqtt_ct
        )
        trans.serialization.set(serials)
        trans.save()
        for d in devs:
            d.transport.add(d)
            d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_transportAuth_polymorph'),
    ]

    operations = [
        migrations.RunPython(gather_mqtt, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TransportMQTT',
            fields=[
                ('transportauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.transportauth')),
                ('prefix', models.CharField(blank=True, default='', help_text='Pub/Sub Prefix', max_length=30)),
                ('response_topic', models.CharField(blank=True, default='', help_text='Response Topic', max_length=60)),
                ('broadcast_topic', models.CharField(blank=True, default='', help_text='Broadcast Topic', max_length=60)),
                ('device_topic', models.CharField(blank=True, default='', help_text='Device Topic', max_length=60)),
                ('profile_topic', models.CharField(blank=True, default='', help_text='Broadcast Topic', max_length=60)),
            ],
            options={
                'verbose_name': 'MQTT Transport',
            },
            bases=('device.transportauth',),
        ),
        migrations.RunPython(update_mqtt, migrations.RunPython.noop),
    ]
